name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cocotb
        run: pip install cocotb cocotb-test

      - name: Run tests
        working-directory: test
        run: make
